# -*- coding: utf-8 -*-
"""scheduler.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EexsKrxxyul9j1-nzbUyTyKSLqY9QeiH
"""

!pip install schedule

import schedule
import time
import subprocess
import os

def run_script(script_path):
    print(f"Running {script_path} at {time.strftime('%Y-%m-%d %H:%M:%S')}")
    try:
        result = subprocess.run(['python', script_path], capture_output=True, text=True)
        if result.returncode == 0:
            print(f"Successfully executed {script_path}")
            print(f"Output: {result.stdout[:500]}...")  # Show first 500 chars
        else:
            print(f"Error executing {script_path}")
            print(f"Error: {result.stderr}")
    except Exception as e:
        print(f"Exception occurred while running {script_path}: {e}")

# Define your script paths
script1 = "/content/drive/MyDrive/Colab Notebooks/Sentiment Analysis/data_collection/mastodon_data_collection.py"
script2 = "/content/drive/MyDrive/Colab Notebooks/Sentiment Analysis/data_collection/youtube_data_collection.py"
script3 = "/content/drive/MyDrive/Colab Notebooks/Sentiment Analysis/Speed Layer (Real-Time Processing with Spark).py"

# Verify scripts exist
for script in [script1, script2, script3]:
    if not os.path.exists(script):
        print(f"WARNING: Script {script} not found!")

# Schedule scripts to run every hour
schedule.every().hour.do(lambda: run_script(script1))
schedule.every().hour.do(lambda: run_script(script2))
schedule.every().hour.do(lambda: run_script(script3))

# Run scripts immediately
print("Running scripts immediately first time...")
run_script(script1)
run_script(script2)
run_script(script3)

# Keep the notebook running and execute the scheduled tasks
print("Starting scheduler - scripts will run hourly...")
while True:
    schedule.run_pending()
    time.sleep(60)  # Check every minute

